### PR TITLE
Resolved #46 and #41. Added error exceptions for motor controller ini…

### LINKED ISSUE #41: Exception Handling For Objects in DriveTrain Class
There are several objects in the DriveTrain class such as the TalonSRX's and the NavX gyro that currently have no exception handling. Add in exception handling for constructing these so that the Driver Station will be sent messages if any of the devices are not connected / sending signals to the roborio. 

Examples of how to do this exception handling can be found in the 2018 DriveTrain code.

### LINKED ISSUE #46: Store Deadzones In Value For Rotation
In The worldOfTanksDrive method in DriveTrain, there is a deadzone check for if the joysticks are in the deadzone, store this deadzone value in a single value.

### PR DESCRIPTION
**Pull request by SHS-Programmers**
Resolved #46 and #41. Added error exceptions for motor controller initialization. removed unused imports.

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/Intake.java [hunk 1]
```diff
@@ -30,9 +31,14 @@
   }
 
   public Intake() {
-    limitSwitch = new DigitalInput(limitSwitchPort);
-    jointMotor = new VictorSP(jointMotorPort);
-    intakeMotor = new VictorSP(intakeMotorPort);
+    try {
+
```
Comment (Dustin-Klein) [inline src/main/java/frc/robot/subsystems/Intake.java]: bad space

**Review by Dustin-Klein — COMMENTED** [review]
Why are you deleting all our auto modes?

**Review by BEF-BEF — APPROVED** [review]
